#!/usr/bin/env bash
#script show info of subdomains

#get domain and subdomain
domain="$1"
subdomain="$2"

domain_config ()
{
	script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ] 
then
	domain_config "$1" "www"
	domain_config "$1" "lb-01"
	domain_config "$1" "web-01"
	domain_config "$1" "web-02"
elif [ "$#" == 2 ]
then
	domain_config "$1" "$2"
fi
