#!/usr/bin/env bash
# This script retrieves DNS information for specified subdomains of a given domain

print_info () {
    local domain="$1"
    local subdomain="$2"
    local script
    script=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $NF}')
    echo "The subdomain $subdomain is a A record and points to $script"
}

if [ "$#" -eq 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        print_info "$1" "$subdomain"
    done
elif [ "$#" -eq 2 ]; then
    print_info "$1" "$2"
fi
