#!/bin/bash

# Check if an IP address is provided as an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the argument
ip_address="$1"

# Ping the IP address 5 times and display the results
echo "PING $ip_address"
ping -c 5 "$ip_address"

exit 0

